
##########################################
#     Change these variables !important
##########################################

# Set this for Copyright in the footer
owner: Ry Auscitte

# Optional quote in the footer
# To disable set enable to false
quote:
  enable: true
  quote: Arthur felt happy. He was terribly pleased that the day was for once working out so much according to plan. Only twenty minutes ago he had decided he would go mad, and now here he was already chasing a Chesterfield sofa across the fields of prehistoric Earth.
  author: Douglas Adams, Life, the Universe and Everything 

# Set this to your main site title. If page doesn't have its own title,
# then this title will be used.
title: A Cosy Home for My Notes


# Following needed for disqus integration
# Set your 'disqus' account name
disqus: auscitte-github-io

# Uncomment if deployed locally
#url: https://localhost:4000

# Set your host if deployed not locally
# For example "https://yourGitHub.github.io"
url: https://auscitte.github.io

# Change this to your base URL starting with forward slash if site is in gh-pages branch
# For example /branchName
# NOTE! only change if site is NOT in master's branch
#baseurl: 

# Change this to your google analytics ID
google_analytics:

# Contact form pupublic key
contact_PK:


##########################################
#          Optional variables
##########################################

# Set maximum posts per page
paginate: 10

# Set permalink
permalink: /:categories/:title

# MathJax support
math: true

collections:
- definitions


highlighter_class_name: "highlight"
#syntax_highlighter_opts seems to have no effect on {% highlight %}
#syntax_highlighter_opts:
#  css_class: "{{ highlighter_class_name }}"

##########################################
#          Do not change these variables
##########################################

include:
  - _pages

sass:
  sass_dir: _sass
sass:
    style: compressed

gems:
  - jekyll-paginate
  - jekyll-sitemap # add /sitemap.xml file

paginate_path: /_pages/page:num

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
